// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0gHFmjmmz3t6UN28LfpVO93K4suMsVVE',
    appId: '1:139587240260:web:bc064e1fe7d41d00f19711',
    messagingSenderId: '139587240260',
    projectId: 'ootd-practice',
    authDomain: 'ootd-practice.firebaseapp.com',
    storageBucket: 'ootd-practice.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0xVkcrcmKtdSMc7NtjKcJi4-pDWWhoJk',
    appId: '1:139587240260:android:efd7b038b2379a88f19711',
    messagingSenderId: '139587240260',
    projectId: 'ootd-practice',
    storageBucket: 'ootd-practice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmv-qG8YPOduGYfiU6qLfJrAAGR4lgDFg',
    appId: '1:139587240260:ios:634761f660fcdf22f19711',
    messagingSenderId: '139587240260',
    projectId: 'ootd-practice',
    storageBucket: 'ootd-practice.firebasestorage.app',
    iosBundleId: 'com.example.outfitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmv-qG8YPOduGYfiU6qLfJrAAGR4lgDFg',
    appId: '1:139587240260:ios:634761f660fcdf22f19711',
    messagingSenderId: '139587240260',
    projectId: 'ootd-practice',
    storageBucket: 'ootd-practice.firebasestorage.app',
    iosBundleId: 'com.example.outfitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0gHFmjmmz3t6UN28LfpVO93K4suMsVVE',
    appId: '1:139587240260:web:77a35111ff68b366f19711',
    messagingSenderId: '139587240260',
    projectId: 'ootd-practice',
    authDomain: 'ootd-practice.firebaseapp.com',
    storageBucket: 'ootd-practice.firebasestorage.app',
  );

}