// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcMru4URqSRQ29wzvDXywKZ3pEhFxwFLA',
    appId: '1:818537384832:web:f1b295eb2a7787ce66cf65',
    messagingSenderId: '818537384832',
    projectId: 'ootd-project-4cfd2',
    authDomain: 'ootd-project-4cfd2.firebaseapp.com',
    storageBucket: 'ootd-project-4cfd2.firebasestorage.app',
    measurementId: 'G-NBC5MKC3L0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaBc7pF6cCJz2SnRRiNzxGtTlLa0WGjcY',
    appId: '1:818537384832:android:1dd102e296e7027866cf65',
    messagingSenderId: '818537384832',
    projectId: 'ootd-project-4cfd2',
    storageBucket: 'ootd-project-4cfd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB60LHbbmsu2yN0erRlKV-oZMlBJIh7RbY',
    appId: '1:818537384832:ios:965473dc3a18a30c66cf65',
    messagingSenderId: '818537384832',
    projectId: 'ootd-project-4cfd2',
    storageBucket: 'ootd-project-4cfd2.firebasestorage.app',
    iosBundleId: 'com.example.outfitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB60LHbbmsu2yN0erRlKV-oZMlBJIh7RbY',
    appId: '1:818537384832:ios:965473dc3a18a30c66cf65',
    messagingSenderId: '818537384832',
    projectId: 'ootd-project-4cfd2',
    storageBucket: 'ootd-project-4cfd2.firebasestorage.app',
    iosBundleId: 'com.example.outfitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcMru4URqSRQ29wzvDXywKZ3pEhFxwFLA',
    appId: '1:818537384832:web:6d14b3ad24061ab766cf65',
    messagingSenderId: '818537384832',
    projectId: 'ootd-project-4cfd2',
    authDomain: 'ootd-project-4cfd2.firebaseapp.com',
    storageBucket: 'ootd-project-4cfd2.firebasestorage.app',
    measurementId: 'G-YPLNXPJZ33',
  );
}
